"""
audit_images.py — Walk the local images/ folder, measure how much of each
420x420 frame the can actually fills, and emit a SQL file that flags
under-filled images as 'needs_review'.

Run:
    cd seltzer_database
    python audit_images.py [min_fill_fraction]

Default min_fill = 0.60 — images where the can's bbox dimensions are both
smaller than 60% of 420px get flagged. Outputs flag_images.sql for you
to run in the Supabase SQL editor.
"""
import json, os, re, sys, unicodedata
from PIL import Image


def slug(s):
    s = unicodedata.normalize('NFKD', s).encode('ascii', 'ignore').decode('ascii')
    return re.sub(r'[^a-z0-9]+', '-', s.lower()).strip('-')


def sqlesc(s):
    return s.replace("'", "''")


def main():
    min_fill = float(sys.argv[1]) if len(sys.argv) > 1 else 0.60
    threshold = int(420 * min_fill)
    print(f'Flagging images where max(content_w, content_h) < {threshold}px '
          f'({min_fill*100:.0f}% of 420)')

    seltzers = json.load(open('seltzers.json', encoding='utf-8'))
    flagged = []
    ok = []
    for r in seltzers:
        fn = r.get('image_filename')
        if not fn or not os.path.exists(os.path.join('images', fn)):
            continue
        img = Image.open(os.path.join('images', fn)).convert('RGB')
        gray = img.convert('L')
        mask = gray.point(lambda p: 0 if p > 240 else 255)
        bbox = mask.getbbox()
        if not bbox:
            flagged.append(r)
            continue
        w = bbox[2] - bbox[0]
        h = bbox[3] - bbox[1]
        if max(w, h) < threshold:
            flagged.append({**r, '_dims': f'{w}x{h}'})
        else:
            ok.append(r)

    print(f'OK: {len(ok)}, flagged: {len(flagged)}')

    # Emit SQL
    lines = [
        '-- Auto-generated by audit_images.py',
        '-- Marks under-filled canonical images for curator review.',
        '-- Run after supabase_standardize_data.sql.',
        '',
        '-- Reset prior flags first',
        "update public.seltzers set image_quality_flag = null where image_quality_flag = 'needs_review';",
        '',
        '-- Flag these as needs_review',
    ]
    for r in flagged:
        lines.append(
            f"update public.seltzers set image_quality_flag = 'needs_review' "
            f"where lower(brand) = lower('{sqlesc(r['brand'])}') "
            f"and lower(name) = lower('{sqlesc(r['name'])}');"
        )
    lines.append('')
    lines.append(f'-- {len(flagged)} rows flagged. {len(ok)} look ok.')
    with open('flag_images.sql', 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print(f'wrote flag_images.sql ({len(flagged)} flagged rows)')


if __name__ == '__main__':
    main()
