-- Seltzer canonical-catalogue seed (184 SKUs)
-- Run this in the Supabase SQL editor.
-- After uploading images/ to the review-images bucket (in subfolder canonical/),
-- run link_images.sql to fill in image_url for every row.

insert into public.seltzers (brand, name) values
  ('LaCroix', 'Pamplemousse'),
  ('LaCroix', 'Lime'),
  ('LaCroix', 'Lemon'),
  ('LaCroix', 'Orange'),
  ('LaCroix', 'Berry'),
  ('LaCroix', 'Coconut'),
  ('LaCroix', 'Cherry Lime'),
  ('LaCroix', 'Key Lime'),
  ('LaCroix', 'Tangerine'),
  ('LaCroix', 'Passionfruit'),
  ('LaCroix', 'Peach-Pear'),
  ('LaCroix', 'Razz-Cranberry'),
  ('LaCroix', 'Pure'),
  ('LaCroix', 'Mojito'),
  ('LaCroix', 'LimonCello'),
  ('LaCroix', 'Pastèque'),
  ('LaCroix', 'Sunshine'),
  ('LaCroix', 'Beach Plum'),
  ('LaCroix', 'Black Razzberry'),
  ('LaCroix', 'Blackberry Cucumber'),
  ('LaCroix', 'Pineapple Coconut'),
  ('LaCroix', 'Strawberry Peach'),
  ('LaCroix', 'Guava São Paulo'),
  ('Bubly', 'Blackberry'),
  ('Bubly', 'Lime'),
  ('Bubly', 'Cherry'),
  ('Bubly', 'Grapefruit'),
  ('Bubly', 'Raspberry'),
  ('Bubly', 'Strawberry'),
  ('Bubly', 'Mango'),
  ('Bubly', 'Cranberry'),
  ('Bubly', 'Pineapple'),
  ('Bubly', 'Apple'),
  ('Bubly', 'Peach'),
  ('Bubly', 'Watermelon'),
  ('Bubly', 'Coconut Pineapple'),
  ('Bubly', 'Orange Cream'),
  ('Bubly', 'Strawberry Sunset'),
  ('Bubly', 'Bellini Bliss'),
  ('Bubly', 'Cosmic Swirl'),
  ('Bubly', 'Dragon Fruit Stardust'),
  ('Bubly', 'Meteor Melon'),
  ('AHA', 'Lime + Watermelon'),
  ('AHA', 'Citrus + Green Tea'),
  ('AHA', 'Strawberry + Cucumber'),
  ('AHA', 'Apple + Ginger'),
  ('AHA', 'Blueberry + Pomegranate'),
  ('AHA', 'Black Cherry + Coffee'),
  ('AHA', 'Mango + Black Tea'),
  ('AHA', 'Peach + Honey'),
  ('AHA', 'Orange + Grapefruit'),
  ('AHA', 'Raspberry + Açaí'),
  ('AHA', 'Pineapple + Passionfruit'),
  ('AHA', 'Mixed Berry'),
  ('Spindrift', 'Lemon'),
  ('Spindrift', 'Lime'),
  ('Spindrift', 'Grapefruit'),
  ('Spindrift', 'Cucumber'),
  ('Spindrift', 'Orange Mango'),
  ('Spindrift', 'Half-and-Half'),
  ('Spindrift', 'Raspberry Lime'),
  ('Spindrift', 'Pineapple'),
  ('Spindrift', 'Strawberry'),
  ('Spindrift', 'Cranberry Raspberry'),
  ('Spindrift', 'Blackberry'),
  ('Spindrift', 'Black Cherry Tangerine'),
  ('Polar', 'Lime'),
  ('Polar', 'Black Cherry'),
  ('Polar', 'Lemon'),
  ('Polar', 'Original'),
  ('Polar', 'Cranberry Lime'),
  ('Polar', 'Orange Vanilla'),
  ('Polar', 'Mango Lemonade'),
  ('Polar', 'Raspberry Lime'),
  ('Polar', 'Strawberry Watermelon'),
  ('Polar', 'Pomegranate'),
  ('Polar', 'Blueberry Lemonade'),
  ('Polar', 'Toasted Coconut'),
  ('Polar', 'Mixed Berry'),
  ('Polar', 'Ruby Red Grapefruit'),
  ('Polar', 'Vanilla Zen'),
  ('Waterloo', 'Black Cherry'),
  ('Waterloo', 'Pineapple Mango'),
  ('Waterloo', 'Strawberry'),
  ('Waterloo', 'Lemon Lime'),
  ('Waterloo', 'Watermelon'),
  ('Waterloo', 'Coconut'),
  ('Waterloo', 'Lemon'),
  ('Waterloo', 'Lime'),
  ('Waterloo', 'Grape'),
  ('Waterloo', 'Blueberry'),
  ('Waterloo', 'Tangerine'),
  ('Waterloo', 'Peach'),
  ('Waterloo', 'Raspberry'),
  ('Waterloo', 'Pomegranate'),
  ('Waterloo', 'Summer Berry'),
  ('Waterloo', 'Ginger Citrus Twist'),
  ('San Pellegrino', 'Sparkling Mineral Water'),
  ('San Pellegrino', 'Limonata'),
  ('San Pellegrino', 'Aranciata'),
  ('San Pellegrino', 'Aranciata Rossa'),
  ('San Pellegrino', 'Pompelmo'),
  ('San Pellegrino', 'Clementina'),
  ('San Pellegrino', 'Limone & Menta'),
  ('San Pellegrino', 'Pesca-Tea'),
  ('San Pellegrino', 'Melograno & Arancia'),
  ('San Pellegrino', 'Ficodindia & Arancia'),
  ('Perrier', 'Original'),
  ('Perrier', 'Lime'),
  ('Perrier', 'Lemon'),
  ('Perrier', 'Pomegranate'),
  ('Perrier', 'Strawberry'),
  ('Perrier', 'Pineapple'),
  ('Perrier', 'Grapefruit'),
  ('Perrier', 'Peach'),
  ('Perrier', 'Watermelon'),
  ('Topo Chico', 'Mineral Water'),
  ('Topo Chico', 'Twist of Lime'),
  ('Topo Chico', 'Twist of Grapefruit'),
  ('Topo Chico', 'Strawberry Guava'),
  ('Topo Chico', 'Tangy Lemon Lime'),
  ('Schweppes', 'Club Soda'),
  ('Schweppes', 'Tonic Water'),
  ('Schweppes', 'Diet Tonic Water'),
  ('Schweppes', 'Ginger Ale'),
  ('Schweppes', 'Diet Ginger Ale'),
  ('Schweppes', 'Raspberry Ginger Ale'),
  ('Schweppes', 'Lemon-Lime Sparkling Water'),
  ('Schweppes', 'Black Cherry Sparkling Water'),
  ('Schweppes', 'Raspberry Lime Sparkling Water'),
  ('Canada Dry', 'Ginger Ale'),
  ('Canada Dry', 'Diet Ginger Ale'),
  ('Canada Dry', 'Cranberry Ginger Ale'),
  ('Canada Dry', 'Lemon Ginger Ale'),
  ('Canada Dry', 'Tonic Water'),
  ('Canada Dry', 'Club Soda'),
  ('Canada Dry', 'Bold Ginger Ale'),
  ('Liquid Death', 'Sparkling Water'),
  ('Liquid Death', 'Severed Lime'),
  ('Liquid Death', 'Berry It Alive'),
  ('Liquid Death', 'Convicted Melon'),
  ('Liquid Death', 'Mango Chainsaw'),
  ('Sanzo', 'Lychee'),
  ('Sanzo', 'Mango'),
  ('Sanzo', 'Yuzu Ginger'),
  ('Sanzo', 'Calamansi'),
  ('Sanzo', 'Strawberry Lychee'),
  ('Sanzo', 'Pomelo Pink Lemonade'),
  ('Nixie', 'Tropical Coconut'),
  ('Nixie', 'Tangerine'),
  ('Nixie', 'Black Cherry'),
  ('Nixie', 'Lemon Lime Mint'),
  ('Nixie', 'Watermelon Strawberry'),
  ('Nixie', 'Citrus Twist'),
  ('Nixie', 'Grapefruit'),
  ('Nixie', 'Cucumber Melon'),
  ('Hal''s New York', 'Black Cherry'),
  ('Hal''s New York', 'Berry'),
  ('Hal''s New York', 'Lemon-Lime'),
  ('Hal''s New York', 'Mango'),
  ('Hal''s New York', 'Mixed Berry'),
  ('Hal''s New York', 'Pomegranate'),
  ('Hal''s New York', 'Raspberry'),
  ('Hal''s New York', 'Strawberry'),
  ('Hal''s New York', 'Watermelon'),
  ('Hal''s New York', 'Apple'),
  ('Hal''s New York', 'Mandarin Orange'),
  ('Hal''s New York', 'Cherry Vanilla'),
  ('Hal''s New York', 'Cucumber Watermelon'),
  ('Hal''s New York', 'Vanilla Cream'),
  ('Hal''s New York', 'Toasted Coconut'),
  ('Hal''s New York', 'Blueberry Lemon'),
  ('Hal''s New York', 'Lemon'),
  ('Hal''s New York', 'Lime'),
  ('Kirkland Signature', 'Sparkling Water Lime'),
  ('Kirkland Signature', 'Sparkling Water Grapefruit'),
  ('Kirkland Signature', 'Sparkling Water Black Cherry'),
  ('Kirkland Signature', 'Sparkling Water Original'),
  ('Rambler', 'Lime'),
  ('Rambler', 'Original'),
  ('Rambler', 'Grapefruit'),
  ('Rambler', 'Watermelon'),
  ('Rambler', 'Lemon'),
  ('Rambler', 'Black Cherry')
on conflict do nothing;