-- Seltzer canonical-catalogue seed (318 SKUs, normalized)
-- Run after supabase_standardize_data.sql.

insert into public.seltzers (brand, name) values
  ('LaCroix', 'Pamplemousse'),
  ('LaCroix', 'Lime'),
  ('LaCroix', 'Lemon'),
  ('LaCroix', 'Orange'),
  ('LaCroix', 'Berry'),
  ('LaCroix', 'Coconut'),
  ('LaCroix', 'Cherry Lime'),
  ('LaCroix', 'Key Lime'),
  ('LaCroix', 'Tangerine'),
  ('LaCroix', 'Passionfruit'),
  ('LaCroix', 'Peach-Pear'),
  ('LaCroix', 'Razz Cranberry'),
  ('LaCroix', 'Pure'),
  ('LaCroix', 'Mojito'),
  ('LaCroix', 'LimonCello'),
  ('LaCroix', 'Pastèque'),
  ('LaCroix', 'Sunshine'),
  ('LaCroix', 'Beach Plum'),
  ('LaCroix', 'Black Razzberry'),
  ('LaCroix', 'Blackberry Cucumber'),
  ('LaCroix', 'Pineapple Coconut'),
  ('LaCroix', 'Strawberry Peach'),
  ('LaCroix', 'Guava São Paulo'),
  ('Bubly', 'Blackberry'),
  ('Bubly', 'Lime'),
  ('Bubly', 'Cherry'),
  ('Bubly', 'Grapefruit'),
  ('Bubly', 'Raspberry'),
  ('Bubly', 'Strawberry'),
  ('Bubly', 'Mango'),
  ('Bubly', 'Cranberry'),
  ('Bubly', 'Pineapple'),
  ('Bubly', 'Apple'),
  ('Bubly', 'Peach'),
  ('Bubly', 'Watermelon'),
  ('Bubly', 'Coconut Pineapple'),
  ('Bubly', 'Orange Cream'),
  ('Bubly', 'Strawberry Sunset'),
  ('Bubly', 'Bellini Bliss'),
  ('Bubly', 'Cosmic Swirl'),
  ('Bubly', 'Dragon Fruit Stardust'),
  ('Bubly', 'Meteor Melon'),
  ('AHA', 'Lime Watermelon'),
  ('AHA', 'Citrus Green Tea'),
  ('AHA', 'Strawberry Cucumber'),
  ('AHA', 'Apple Ginger'),
  ('AHA', 'Blueberry Pomegranate'),
  ('AHA', 'Black Cherry Coffee'),
  ('AHA', 'Mango Black Tea'),
  ('AHA', 'Peach Honey'),
  ('AHA', 'Orange Grapefruit'),
  ('AHA', 'Raspberry Açaí'),
  ('AHA', 'Pineapple Passionfruit'),
  ('AHA', 'Mixed Berry'),
  ('Spindrift', 'Lemon'),
  ('Spindrift', 'Lime'),
  ('Spindrift', 'Grapefruit'),
  ('Spindrift', 'Cucumber'),
  ('Spindrift', 'Orange Mango'),
  ('Spindrift', 'Half-and-Half'),
  ('Spindrift', 'Raspberry Lime'),
  ('Spindrift', 'Pineapple'),
  ('Spindrift', 'Strawberry'),
  ('Spindrift', 'Cranberry Raspberry'),
  ('Spindrift', 'Blackberry'),
  ('Spindrift', 'Black Cherry Tangerine'),
  ('Polar', 'Lime'),
  ('Polar', 'Black Cherry'),
  ('Polar', 'Lemon'),
  ('Polar', 'Original'),
  ('Polar', 'Cranberry Lime'),
  ('Polar', 'Orange Vanilla'),
  ('Polar', 'Mango Lemonade'),
  ('Polar', 'Raspberry Lime'),
  ('Polar', 'Strawberry Watermelon'),
  ('Polar', 'Pomegranate'),
  ('Polar', 'Blueberry Lemonade'),
  ('Polar', 'Toasted Coconut'),
  ('Polar', 'Mixed Berry'),
  ('Polar', 'Ruby Red Grapefruit'),
  ('Polar', 'Vanilla Zen'),
  ('Waterloo', 'Black Cherry'),
  ('Waterloo', 'Pineapple Mango'),
  ('Waterloo', 'Strawberry'),
  ('Waterloo', 'Lemon Lime'),
  ('Waterloo', 'Watermelon'),
  ('Waterloo', 'Coconut'),
  ('Waterloo', 'Lemon'),
  ('Waterloo', 'Lime'),
  ('Waterloo', 'Grape'),
  ('Waterloo', 'Blueberry'),
  ('Waterloo', 'Tangerine'),
  ('Waterloo', 'Peach'),
  ('Waterloo', 'Raspberry'),
  ('Waterloo', 'Pomegranate'),
  ('Waterloo', 'Summer Berry'),
  ('Waterloo', 'Ginger Citrus Twist'),
  ('San Pellegrino', 'Sparkling Mineral Water'),
  ('San Pellegrino', 'Limonata'),
  ('San Pellegrino', 'Aranciata'),
  ('San Pellegrino', 'Aranciata Rossa'),
  ('San Pellegrino', 'Pompelmo'),
  ('San Pellegrino', 'Clementina'),
  ('San Pellegrino', 'Limone & Menta'),
  ('San Pellegrino', 'Pesca-Tea'),
  ('San Pellegrino', 'Melograno & Arancia'),
  ('San Pellegrino', 'Ficodindia & Arancia'),
  ('Perrier', 'Original'),
  ('Perrier', 'Lime'),
  ('Perrier', 'Lemon'),
  ('Perrier', 'Pomegranate'),
  ('Perrier', 'Strawberry'),
  ('Perrier', 'Pineapple'),
  ('Perrier', 'Grapefruit'),
  ('Perrier', 'Peach'),
  ('Perrier', 'Watermelon'),
  ('Topo Chico', 'Mineral Water'),
  ('Topo Chico', 'Twist of Lime'),
  ('Topo Chico', 'Twist of Grapefruit'),
  ('Topo Chico', 'Strawberry Guava'),
  ('Topo Chico', 'Tangy Lemon Lime'),
  ('Schweppes', 'Club Soda'),
  ('Schweppes', 'Tonic Water'),
  ('Schweppes', 'Diet Tonic Water'),
  ('Schweppes', 'Ginger Ale'),
  ('Schweppes', 'Diet Ginger Ale'),
  ('Schweppes', 'Raspberry Ginger Ale'),
  ('Schweppes', 'Lemon Lime Sparkling Water'),
  ('Schweppes', 'Black Cherry Sparkling Water'),
  ('Schweppes', 'Raspberry Lime Sparkling Water'),
  ('Canada Dry', 'Ginger Ale'),
  ('Canada Dry', 'Diet Ginger Ale'),
  ('Canada Dry', 'Cranberry Ginger Ale'),
  ('Canada Dry', 'Lemon Ginger Ale'),
  ('Canada Dry', 'Tonic Water'),
  ('Canada Dry', 'Club Soda'),
  ('Canada Dry', 'Bold Ginger Ale'),
  ('Liquid Death', 'Sparkling Water'),
  ('Liquid Death', 'Severed Lime'),
  ('Liquid Death', 'Berry It Alive'),
  ('Liquid Death', 'Convicted Melon'),
  ('Liquid Death', 'Mango Chainsaw'),
  ('Sanzo', 'Lychee'),
  ('Sanzo', 'Mango'),
  ('Sanzo', 'Yuzu Ginger'),
  ('Sanzo', 'Calamansi'),
  ('Sanzo', 'Strawberry Lychee'),
  ('Sanzo', 'Pomelo Pink Lemonade'),
  ('Nixie', 'Tropical Coconut'),
  ('Nixie', 'Tangerine'),
  ('Nixie', 'Black Cherry'),
  ('Nixie', 'Lemon Lime Mint'),
  ('Nixie', 'Watermelon Strawberry'),
  ('Nixie', 'Citrus Twist'),
  ('Nixie', 'Grapefruit'),
  ('Nixie', 'Cucumber Melon'),
  ('Hal''s New York', 'Black Cherry'),
  ('Hal''s New York', 'Berry'),
  ('Hal''s New York', 'Lemon Lime'),
  ('Hal''s New York', 'Mango'),
  ('Hal''s New York', 'Mixed Berry'),
  ('Hal''s New York', 'Pomegranate'),
  ('Hal''s New York', 'Raspberry'),
  ('Hal''s New York', 'Strawberry'),
  ('Hal''s New York', 'Watermelon'),
  ('Hal''s New York', 'Apple'),
  ('Hal''s New York', 'Mandarin Orange'),
  ('Hal''s New York', 'Cherry Vanilla'),
  ('Hal''s New York', 'Cucumber Watermelon'),
  ('Hal''s New York', 'Vanilla Cream'),
  ('Hal''s New York', 'Toasted Coconut'),
  ('Hal''s New York', 'Blueberry Lemon'),
  ('Hal''s New York', 'Lemon'),
  ('Hal''s New York', 'Lime'),
  ('Kirkland Signature', 'Sparkling Water Lime'),
  ('Kirkland Signature', 'Sparkling Water Grapefruit'),
  ('Kirkland Signature', 'Sparkling Water Black Cherry'),
  ('Kirkland Signature', 'Sparkling Water Original'),
  ('Rambler', 'Lime'),
  ('Rambler', 'Original'),
  ('Rambler', 'Grapefruit'),
  ('Rambler', 'Watermelon'),
  ('Rambler', 'Lemon'),
  ('Rambler', 'Black Cherry'),
  ('Trader Joe''s', 'Sparkling Water Original'),
  ('Trader Joe''s', 'Sparkling Water Lime'),
  ('Trader Joe''s', 'Sparkling Water Grapefruit'),
  ('Trader Joe''s', 'Sparkling Water Lemon'),
  ('Trader Joe''s', 'Triple Ginger Brew'),
  ('Trader Joe''s', 'Sparkling Yuzu'),
  ('Trader Joe''s', 'Sparkling Coconut Water'),
  ('Trader Joe''s', 'Sparkling Mint Mojito'),
  ('Good & Gather', 'Lime Sparkling Water'),
  ('Good & Gather', 'Black Cherry Sparkling Water'),
  ('Good & Gather', 'Lemon Sparkling Water'),
  ('Good & Gather', 'Strawberry Sparkling Water'),
  ('Good & Gather', 'Mango Sparkling Water'),
  ('Good & Gather', 'Cranberry Sparkling Water'),
  ('Good & Gather', 'Mixed Berry Sparkling Water'),
  ('Good & Gather', 'Grapefruit Sparkling Water'),
  ('Good & Gather', 'Pomegranate Sparkling Water'),
  ('Good & Gather', 'Coconut Pineapple Sparkling Water'),
  ('365 by Whole Foods', 'Sparkling Water Original'),
  ('365 by Whole Foods', 'Sparkling Water Lime'),
  ('365 by Whole Foods', 'Sparkling Water Lemon'),
  ('365 by Whole Foods', 'Sparkling Water Cherry Lime'),
  ('365 by Whole Foods', 'Sparkling Water Cranberry Lime'),
  ('365 by Whole Foods', 'Sparkling Water Grapefruit'),
  ('365 by Whole Foods', 'Sparkling Water Mango'),
  ('Member''s Mark', 'Sparkling Water Original'),
  ('Member''s Mark', 'Sparkling Water Lime'),
  ('Member''s Mark', 'Sparkling Water Lemon'),
  ('Member''s Mark', 'Sparkling Water Black Cherry'),
  ('Member''s Mark', 'Sparkling Water Grapefruit'),
  ('Member''s Mark', 'Sparkling Water Mango Pineapple'),
  ('Member''s Mark', 'Sparkling Water Variety Pack'),
  ('Clear American', 'Original Sparkling Water'),
  ('Clear American', 'Strawberry'),
  ('Clear American', 'Mandarin Orange'),
  ('Clear American', 'Black Cherry'),
  ('Clear American', 'Lemon'),
  ('Clear American', 'Grape'),
  ('Clear American', 'Piña Colada'),
  ('Clear American', 'Tropical Punch'),
  ('Clear American', 'Cherry Limeade'),
  ('Clear American', 'Peach'),
  ('Clear American', 'Key Lime'),
  ('Clear American', 'Watermelon'),
  ('Sparkling Ice', 'Black Raspberry'),
  ('Sparkling Ice', 'Cherry Limeade'),
  ('Sparkling Ice', 'Coconut Pineapple'),
  ('Sparkling Ice', 'Crisp Apple'),
  ('Sparkling Ice', 'Strawberry Watermelon'),
  ('Sparkling Ice', 'Peach Nectarine'),
  ('Sparkling Ice', 'Pink Grapefruit'),
  ('Sparkling Ice', 'Orange Mango'),
  ('Sparkling Ice', 'Classic Lemonade'),
  ('Sparkling Ice', 'Kiwi Strawberry'),
  ('Sparkling Ice', 'Black Cherry'),
  ('Sparkling Ice', 'Lemon Lime'),
  ('Sparkling Ice', 'Pomegranate Blueberry'),
  ('Sparkling Ice', 'Strawberry Lemonade'),
  ('Hint', 'Watermelon'),
  ('Hint', 'Blackberry'),
  ('Hint', 'Pineapple'),
  ('Hint', 'Pomegranate'),
  ('Hint', 'Cherry'),
  ('Hint', 'Mango Grapefruit'),
  ('Hint', 'Cucumber'),
  ('Hint', 'Strawberry Kiwi'),
  ('Hint', 'Peach'),
  ('Klarbrunn', 'Black Cherry'),
  ('Klarbrunn', 'Lemon'),
  ('Klarbrunn', 'Lime'),
  ('Klarbrunn', 'Cranberry Lime'),
  ('Klarbrunn', 'Peach'),
  ('Klarbrunn', 'Pineapple Coconut'),
  ('Klarbrunn', 'Strawberry'),
  ('Klarbrunn', 'Mandarin'),
  ('Klarbrunn', 'Original'),
  ('Recess', 'Pomegranate Hibiscus'),
  ('Recess', 'Blackberry Chai'),
  ('Recess', 'Coconut Lime'),
  ('Recess', 'Peach Ginger'),
  ('Recess', 'Black Cherry'),
  ('Recess', 'Strawberry Rose'),
  ('Olipop', 'Vintage Cola'),
  ('Olipop', 'Strawberry Vanilla'),
  ('Olipop', 'Cherry Vanilla'),
  ('Olipop', 'Orange Squeeze'),
  ('Olipop', 'Classic Root Beer'),
  ('Olipop', 'Tropical Punch'),
  ('Olipop', 'Lemon Lime'),
  ('Olipop', 'Watermelon Lime'),
  ('Olipop', 'Crisp Apple'),
  ('Olipop', 'Cream Soda'),
  ('Olipop', 'Doctor Goodwin'),
  ('Olipop', 'Banana Cream'),
  ('Olipop', 'Ginger Lemon'),
  ('Zevia', 'Cola'),
  ('Zevia', 'Ginger Root Beer'),
  ('Zevia', 'Cherry Cola'),
  ('Zevia', 'Cream Soda'),
  ('Zevia', 'Dr. Zevia'),
  ('Zevia', 'Mountain Zevia'),
  ('Zevia', 'Black Cherry'),
  ('Zevia', 'Strawberry'),
  ('Zevia', 'Ginger Ale'),
  ('Zevia', 'Lemon Lime Twist'),
  ('Zevia', 'Orange'),
  ('Zevia', 'Grape'),
  ('Voss', 'Sparkling Plain'),
  ('Voss', 'Sparkling Lemon Cucumber'),
  ('Voss', 'Sparkling Lime Mint'),
  ('Voss', 'Sparkling Tangerine Lemongrass'),
  ('Bai Bubbles', 'Bolivia Black Cherry'),
  ('Bai Bubbles', 'Jamaica Blood Orange'),
  ('Bai Bubbles', 'Peru Pineapple'),
  ('Bai Bubbles', 'Costa Rica Clementine'),
  ('Bai Bubbles', 'Sao Paulo Strawberry Lemonade'),
  ('Bai Bubbles', 'Bahamas Coconut Lime'),
  ('Phocus', 'Yuzu Lime'),
  ('Phocus', 'Grapefruit'),
  ('Phocus', 'Mint'),
  ('Phocus', 'Mixed Berry'),
  ('Phocus', 'Blood Orange'),
  ('Phocus', 'Cucumber'),
  ('Crystal Geyser', 'Sparkling Mineral Water'),
  ('Crystal Geyser', 'Lemon Sparkling'),
  ('Crystal Geyser', 'Lime Sparkling'),
  ('Crystal Geyser', 'Berry Sparkling'),
  ('Crystal Geyser', 'Orange Sparkling'),
  ('Saratoga', 'Sparkling Water'),
  ('Saratoga', 'Sparkling Lemon'),
  ('Saratoga', 'Sparkling Lime'),
  ('Mountain Valley', 'Sparkling Mineral Water'),
  ('Mountain Valley', 'Sparkling Lime'),
  ('Mountain Valley', 'Sparkling Essence Lemon')
on conflict do nothing;